### PR TITLE
Encode field names as UTF-16

### PR DESCRIPTION
**Pull request by pelme**
Currently, the FDF field names are not properly encoded. This happens to work on Python 2 since implicit ASCII conversion is done. Trying to use non-ASCII field names on Python 2 will crash. On Python 3 the code will crash directly. The explicit Python 3 failure can be seen here: https://travis-ci.org/pelme/fdfgen/jobs/162046689#L208

To be able to add a test for this, I've based this PR on PR #18. The important commits in this PR are  e27583e and 	d17af6a. When #18 is merged I can rebase this PR to only include the relevant fix.

### CODE REVIEW

**Comment by pelme** [comment]
@thraxil do you want to merge this or should I go ahead and do it myself?

**Comment by thraxil** [comment]
You can merge it if you like.

For a bit of context: I wrote fdfgen a looong time ago when I had a project that involved some PDF wrangling. It served its purpose but I haven't actually had any use for it myself ever since. I'm happy to keep it up and push releases to PyPI every now and then, but I don't really do much maintenance on it otherwise.

**Comment by pelme** [comment]
No problem, thanks for giving out permissions and being responsive! It works very well, I just hit this regression when playing with python 3.

**Comment by pelme** [comment]
Feel free to put out a new release :) Or add me on PyPI (andreaspelme) and I can help out to put out releases too.

**Pull request merged**
